# Site settings
title: Kevin Jobin
email: f/xvongwra
domain: kevinjobin1.github.io
url: https://kevinjobin1.github.io/
description: "Kevin Jobin"
keywords: "Web, Mobile, Software, Portfolio"
skills: "Software | Web | Mobile"
meta_author: Jobin Kevin

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: kevinjobin

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffbd18 #80B3FF
  primary-rgb: "255, 189, 24" #"128,179,255"
  primary-dark: d59800 
  secondary: 2c2c2c #FD6E8A
  secondary-dark: 242424 #A2122F

# Footer settings
footer:
  copyright: Kevin Jobin
  location: 
  social: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/kevinjobin1
  - title: linkedin
    url: https://www.linkedin.com/in/kevin-jobin

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: "/:short_year"